version: "3.1"

services:
  resources:
    build:
      context:
        ./resources
    container_name: resources
    volumes:
      - ./resources/res:/usr/share/nginx/html

  entry:
    build:
      context:
        ./entry-server
    ports:
      - "80:80"
    container_name: entry
    depends_on:
      - resources
